RuntimeError: Reported algebraic loop detected in DiagramBuilder:   InputPort[0] (ee_target) of System ::kinova_hardware_interface (kinova_station.hardware_station.KinovaStationHardwareInterface) is direct-feedthrough to   OutputPort[5] (measured_ee_wrench) of System ::kinova_hardware_interface (kinova_station.hardware_station.KinovaStationHardwareInterface) is connected to   InputPort[1] (ee_wrench) of System ::controller (__main__.TwistController) is direct-feedthrough to   OutputPort[3] (gripper_command_type) of System ::controller (__main__.TwistController) is connected to   InputPort[3] (gripper_target_type) of System ::kinova_hardware_interface (kinova_station.hardware_station.KinovaStationHardwareInterface) is direct-feedthrough to   InputPort[0] (ee_target) of System ::kinova_hardware_interface (kinova_station.hardware_station.KinovaStationHardwareInterface) A System may have conservatively reported that one of its output ports depends on an input port, making one of the 'is direct-feedthrough to' lines above spurious.  If that is the case, remove the spurious dependency per the Drake API documentation for declaring output ports. https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_leaf_system.html#DeclareLeafOutputPort_feedthrough